const express=require('express')
const {createProject,getAllProjects,getProjectById,updateProject,deleteProject}=require('../../controllers/admin/project.controller')
const AdminMemberRoute=require('./member.route')
const AdminTaskRoute=require('./task.route')
const router=express.Router()
const{isAdmin}=require('../../middlewares/admin')
const{auth}=require('../../middlewares/auth')
const {IsProjectOwner}=require('../../middlewares/isprojectowner')
const {validate}=require('../../middlewares/validate')
const {createProjectSchema,updateProjectSchema,projectIdParamSchema}=require('../../validations/project.validation')

router.use(auth,isAdmin)
router.post('/',validate(createProjectSchema),createProject)
router.get('/',getAllProjects)
router.get('/:projectId',validate(projectIdParamSchema,'params'),IsProjectOwner,getProjectById)
router.patch('/:projectId',IsProjectOwner,validate(projectIdParamSchema,'params'),validate(updateProjectSchema),updateProject)
router.delete('/:projectId',IsProjectOwner,validate(projectIdParamSchema,'params'),deleteProject)
router.use('/:projectId/members',IsProjectOwner,validate(projectIdParamSchema,'params'),AdminMemberRoute)
router.use('/:projectId/tasks',IsProjectOwner,validate(projectIdParamSchema,'params'),AdminTaskRoute)

module.exports=router